### ISSUE TITLE
Ugg.... AttributeError: module 'bme280' has no attribute 

### ISSUE THREAD

**Issue by kevinkey619** [parautenbach/WeeWX-BME280#2]
What am I doing wrong? I've installed, uninstalled, and reinstalled and still no luck.

ewx[4017] CRITICAL __main__: Caught unrecoverable exception:
weewx[4017] CRITICAL __main__:     ****  module 'bme280' has no attribute 'load_calibration_params'
weewx[4017] CRITICAL __main__:     ****  Traceback (most recent call last):

weewx[4017] CRITICAL __main__:     ****    File "/usr/share/weewx/weewxd", line 147, in main

weewx[4017] CRITICAL __main__:     ****      engine = weewx.engine.StdEngine(config_dict)

weewx[4017] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 93, in __init__

weewx[4017] CRITICAL __main__:     ****      self.loadServices(config_dict)

weewx[4017] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 161, in loadServices

weewx[4017] CRITICAL __main__:     ****      obj = weeutil.weeutil.get_object(svc)(self, config_dict)

weewx[4017] CRITICAL __main__:     ****    File "/usr/share/weewx/user/bme280wx.py", line 61, in __init__

weewx[4017] CRITICAL __main__:     ****      self.calibration_params = bme280.load_calibration_params(self.bus, self.address)

weewx[4017] CRITICAL __main__:     ****  AttributeError: module 'bme280' has no attribute 'load_calibration_params'

weewx[4017] CRITICAL __main__:     ****  Exiting.

**Comment by parautenbach** [comment]
Probably because you're running a newer version of WeeWX than what I've built this against. It seems like there was an interface change. Which version are you running?

I don't actively use this anymore, but I'll see if I can make the necessary changes some time soon.

**Comment by kevinkey619** [comment]
weewx 4.8.0

Thanks.

**Comment by parautenbach** [comment]
I knew this sounded familiar to me and I just remembered: You either don't have the [BME280 Python library](https://pypi.org/project/RPi.bme280/) installed (as per the README), or you have the wrong library installed. You have a file called `bme280.py` somewhere that Python is loading, but it's the wrong library.

**Comment by kevinkey619** [comment]
I've check and I only have the one library.

**Comment by kevinkey619** [comment]
pi@ubuntu:~/Downloads $ pip list | grep -i bme

RPi.bme280           0.2.4
WARNING: There was an error checking the latest version of pip.
pi@ubuntu:~/Downloads $

**Comment by parautenbach** [comment]
In my system I have v0.2.3. Latest version seems to mostly fix an issue with local time vs UTC. 

Go to https://github.com/rm-hull/bme280 and experiment with the scripts there to ensure you can open a Python REPL and interact with your BME280 using this library.
